### ISSUE TITLE
Could not find a version that satisfies the requirement PyQt5

### ISSUE THREAD

**Issue by 174n** [vlomme/Multi-Tacotron-Voice-Cloning#28]
```
  Could not find a version that satisfies the requirement PyQt5 (from -r requirements.txt (line 13)) (from ver
sions: )
No matching distribution found for PyQt5 (from -r requirements.txt (line 13))
```

**Comment by Rundik** [comment]
Ноутбук на гугл коллабе тоже не работает, кстати, но там другие ошибки

**Comment by 174n** [comment]
Оказалось надо было python3 юзать, теперь другая ошибка
```
c2c69a8942/PyQt5-5.15.4.tar.gz (3.3MB)
    100% |████████████████████████████████| 3.3MB 714kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-aqyt59jr/PyQt5/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-aqyt59jr/PyQt5/
```
